// GENERATED by hw/model/v3a_model.py -- initial-guess ROM for v3a_invsqrt
// entry = 1/sqrt((idx+0.5)/16) in Q23.40, idx = top 6 bits of m in [1,4)
function [63:0] lut_rom;
  input [5:0] idx;
  begin
    case (idx)
      6'd0: lut_rom = 64'h0000010000000000;
      6'd1: lut_rom = 64'h0000010000000000;
      6'd2: lut_rom = 64'h0000010000000000;
      6'd3: lut_rom = 64'h0000010000000000;
      6'd4: lut_rom = 64'h0000010000000000;
      6'd5: lut_rom = 64'h0000010000000000;
      6'd6: lut_rom = 64'h0000010000000000;
      6'd7: lut_rom = 64'h0000010000000000;
      6'd8: lut_rom = 64'h0000010000000000;
      6'd9: lut_rom = 64'h0000010000000000;
      6'd10: lut_rom = 64'h0000010000000000;
      6'd11: lut_rom = 64'h0000010000000000;
      6'd12: lut_rom = 64'h0000010000000000;
      6'd13: lut_rom = 64'h0000010000000000;
      6'd14: lut_rom = 64'h0000010000000000;
      6'd15: lut_rom = 64'h0000010000000000;
      6'd16: lut_rom = 64'h000000fc17644160;
      6'd17: lut_rom = 64'h000000f4c866d6ab;
      6'd18: lut_rom = 64'h000000ee133df523;
      6'd19: lut_rom = 64'h000000e7e3ed1955;
      6'd20: lut_rom = 64'h000000e229ec8783;
      6'd21: lut_rom = 64'h000000dcd76dd2c4;
      6'd22: lut_rom = 64'h000000d7e0cec303;
      6'd23: lut_rom = 64'h000000d33c2da0dd;
      6'd24: lut_rom = 64'h000000cee115f242;
      6'd25: lut_rom = 64'h000000cac83f5c3d;
      6'd26: lut_rom = 64'h000000c6eb5a2b1d;
      6'd27: lut_rom = 64'h000000c344e63f04;
      6'd28: lut_rom = 64'h000000bfd011f883;
      6'd29: lut_rom = 64'h000000bc889f5dec;
      6'd30: lut_rom = 64'h000000b96ace22f9;
      6'd31: lut_rom = 64'h000000b673498eac;
      6'd32: lut_rom = 64'h000000b39f1977b2;
      6'd33: lut_rom = 64'h000000b0eb95bcbc;
      6'd34: lut_rom = 64'h000000ae565bc018;
      6'd35: lut_rom = 64'h000000abdd458770;
      6'd36: lut_rom = 64'h000000a97e62346b;
      6'd37: lut_rom = 64'h000000a737ef99e8;
      6'd38: lut_rom = 64'h000000a50854bd7c;
      6'd39: lut_rom = 64'h000000a2ee1d1e1a;
      6'd40: lut_rom = 64'h000000a0e7f49ffb;
      6'd41: lut_rom = 64'h0000009ef4a403bf;
      6'd42: lut_rom = 64'h0000009d130dd36c;
      6'd43: lut_rom = 64'h0000009b422bb377;
      6'd44: lut_rom = 64'h00000099810c093e;
      6'd45: lut_rom = 64'h00000097cecfea98;
      6'd46: lut_rom = 64'h000000962aa94c47;
      6'd47: lut_rom = 64'h0000009493d96699;
      6'd48: lut_rom = 64'h0000009309af48ed;
      6'd49: lut_rom = 64'h000000918b8695f3;
      6'd50: lut_rom = 64'h0000009018c66354;
      6'd51: lut_rom = 64'h0000008eb0e03857;
      6'd52: lut_rom = 64'h0000008d534f2794;
      6'd53: lut_rom = 64'h0000008bff970076;
      6'd54: lut_rom = 64'h0000008ab54395af;
      6'd55: lut_rom = 64'h0000008973e81620;
      6'd56: lut_rom = 64'h000000883b1e7618;
      6'd57: lut_rom = 64'h000000870a86e716;
      6'd58: lut_rom = 64'h00000085e1c75c5d;
      6'd59: lut_rom = 64'h00000084c08b1b0b;
      6'd60: lut_rom = 64'h00000083a6825459;
      6'd61: lut_rom = 64'h000000829361c90a;
      6'd62: lut_rom = 64'h0000008186e27502;
      6'd63: lut_rom = 64'h0000008080c14234;
      default: lut_rom = 64'h0;
    endcase
  end
endfunction
