// -----------------------------------------------------------------------------
// tb_v3a: system-level testbench for v3a_top
//
// Acts like the host driver: writes the job into the accelerator over the
// register bus, starts it, waits for the interrupt, reads the results back.
// Stimulus comes from files generated by hw/model/gen_vectors.py; outputs are
// written to text files that hw/run_hw_tests.py compares against the golden
// model (bit-exact) and against the original double-precision benchmark.
//
//   sim/nbody_in.hex : N, STEPS, DT, then N*7 body words
//   sim/ray0_in.hex  : NRAYS, NSPH, EPS, NSPH*4 sphere words, NRAYS*6 ray words
//   sim/ray1_in.hex  : same format (any-hit / shadow rays)
// -----------------------------------------------------------------------------
`timescale 1ns/1ps
module tb_v3a;
  reg clk = 1'b0;
  always #5 clk = ~clk;                 // 100 MHz
  reg         rst = 1'b1;
  reg  [23:0] addr = 0;
  reg  [63:0] wdata = 0;
  reg         we = 1'b0;
  wire [63:0] rdata;
  wire        irq;

  v3a_top dut (.clk(clk), .rst(rst), .addr(addr), .wdata(wdata), .we(we), .rdata(rdata), .irq(irq));

  localparam [23:0] NB = 24'h000000;
  localparam [23:0] RY = 24'h100000;

  task bus_write(input [23:0] a, input [63:0] d);
    begin
      @(negedge clk); addr = a; wdata = d; we = 1'b1;
      @(negedge clk); we = 1'b0;
    end
  endtask

  task bus_read(input [23:0] a, output [63:0] d);
    begin
      @(negedge clk); addr = a; #1; d = rdata;
    end
  endtask

  task wait_done(input [23:0] base, output [63:0] cyc);
    reg [63:0] st;
    begin
      st = 0;
      while (!st[1]) begin
        @(posedge clk);
        bus_read(base + 24'h1, st);
      end
      bus_read(base + 24'h5 + (base == NB ? 24'h1 : 24'h0), cyc);   // CYCLES
    end
  endtask

  reg [63:0] mem [0:200000];
  integer    n, steps, k, f, fo, nr, ns, s, r, m, cnt;
  reg [63:0] v, cyc;

  // read a hex file (one 64-bit word per line) into mem[]
  task load_hex(input [8*32-1:0] fname);
    begin
      f = $fopen(fname, "r");
      if (f == 0) begin $display("cannot open %0s", fname); $finish; end
      cnt = 0;
      while ($fscanf(f, "%h\n", v) == 1) begin mem[cnt] = v; cnt = cnt + 1; end
      $fclose(f);
    end
  endtask

  task run_ray(input integer mode, input [8*32-1:0] infile, input [8*32-1:0] outfile);
    begin
      load_hex(infile);
      nr = mem[0]; ns = mem[1];
      bus_write(RY + 24'h2, nr);
      bus_write(RY + 24'h3, ns);
      bus_write(RY + 24'h4, mem[2]);
      for (s = 0; s < ns; s = s + 1)
        for (m = 0; m < 4; m = m + 1)
          bus_write(RY + 24'h100 + 4*s + m, mem[3 + 4*s + m]);
      for (r = 0; r < nr; r = r + 1)
        for (m = 0; m < 6; m = m + 1)
          bus_write(RY + 24'h10000 + 8*r + m, mem[3 + 4*ns + 6*r + m]);
      bus_write(RY + 24'h0, 64'h1 | (mode << 1));
      wait_done(RY, cyc);
      fo = $fopen(outfile, "w");
      $fwrite(fo, "%016h\n", cyc);
      for (r = 0; r < nr; r = r + 1) begin
        bus_read(RY + 24'h80000 + 2*r, v); $fwrite(fo, "%016h\n", v);
        bus_read(RY + 24'h80000 + 2*r + 1, v); $fwrite(fo, "%016h\n", v);
      end
      $fclose(fo);
      $display("ray mode %0d: %0d rays x %0d spheres in %0d cycles", mode, nr, ns, cyc);
    end
  endtask

  initial begin
    repeat (4) @(posedge clk);
    rst = 1'b0;

    // ---------------- nbody -----------------------------------------------------------
    load_hex("sim/nbody_in.hex");
    n = mem[0]; steps = mem[1];
    bus_write(NB + 24'h2, n);
    bus_write(NB + 24'h3, steps);
    bus_write(NB + 24'h4, mem[2]);
    for (k = 0; k < n; k = k + 1)
      for (m = 0; m < 7; m = m + 1)
        bus_write(NB + 24'h100 + 8*k + m, mem[3 + 7*k + m]);
    bus_read(NB + 24'h7, v);
    $display("device id %h", v);
    bus_write(NB + 24'h0, 64'h1);
    wait_done(NB, cyc);
    fo = $fopen("sim/nbody_out.hex", "w");
    $fwrite(fo, "%016h\n", cyc);
    for (k = 0; k < n; k = k + 1)
      for (m = 0; m < 7; m = m + 1) begin
        bus_read(NB + 24'h100 + 8*k + m, v);
        $fwrite(fo, "%016h\n", v);
      end
    $fclose(fo);
    $display("nbody: %0d bodies, %0d steps in %0d cycles", n, steps, cyc);

    // ---------------- ray kernels --------------------------------------------------------
    run_ray(0, "sim/ray0_in.hex", "sim/ray0_out.hex");
    run_ray(1, "sim/ray1_in.hex", "sim/ray1_out.hex");

    $finish;
  end
endmodule
